#!/usr/bin/env python3
# -*- mode: python; coding: utf-8 -*-

subdirs = ['client']

def options(opt):
    opt.recurse(subdirs)

def configure(conf):
    conf.recurse(subdirs)

def build(bld):
    bld.recurse(subdirs)
